/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
  //This tests if it returns a String
    @Test
    public void getStringWord(){
      App myApp = new App();
      assertEquals("mimi", myApp.words());
    }

  //This will Test if the random picker works
    @Test
    public void getRandomword(){
      App myApp = new App();
      assertEquals("Tiger", myApp.randWords());
    }

    //This Test will check if the word is split into individual chars
    @Test
    public void checkSplitting(){
      App myApp = new App();
      String[] myVar = {"T","i","g","e","r"};
      assertEquals(myVar, myApp.splitWords("Tiger"));
    }

    //Thistest will breakup the user Input
    @Test
    public void breakupUserInput(){
      App myApp = new App();
      String[] myVar1 ={"T","i","g","e","r"};
      assertEquals(myVar1,myApp.breakupUserInput("Tiger"));
    }
  }
